scala-steward-org/scala-steward-action

Dockerfile

... because sandboxing is disabled. See also https://github.com/scala-steward-org/scala-steward-action/pull/3.

Do not install firejail

---

README.md
action.yml
src/main.ts

- `scala-steward-version`: to allow tweaking the Scala Steward version used
- `ignore-opts-files`: to allow enabling/disabling opts files
- `sign-commits`: to allow enabling/disabling signing commits
This input can be used in conjunction with [crazy-max/ghaction-import-gpg](https://github.com/crazy-max/ghaction-import-gpg) to enable signing Scala Steward commits:
```yaml
- name: Import GPG key
uses: crazy-max/ghaction-import-gpg@v2
with:
git_user_signingkey: true
env:
GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
PASSPHRASE:      ${{ secrets.GPG_PASSPHRASE }}
- uses: scala-steward-org/scala-steward-action@master
with:
github-repository: 'alejandrohdezma/test'
github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
sign-commits: true
```
One of the latest snapshot versions is used currently …

Add more inputs to configure Scala Steward execution

---

action.yml
src/check.ts
src/files.ts
src/main.ts

This PR introduces a new input `repos-file` that will allow users of this action to launch Scala Steward on multiple repositories (instead of just one).
- Add a new input to `action.yml`: `repos-file`.
- This new input will be used to provide the path to a file with the list of repositories to update in Markdown format. [Example](https://github.com/scala-steward-org/repos/blob/master/repos-github.md).
- When present it will take precedence over `github-repository`.
An example of this new feature running on a repository can be found [here](https://github.com/alejandrohdezma/.github/runs/682600969?check_suite_focus=true).
Closes #1

Allow running Scala Steward on multiple repositories

---

.github/workflows/release.yml

This GitHub Action updates major version tags (e.g. v1, v2) when semantic versioning tag is pushed. If v1.2.3 tag is pushed, it updates v1 tag.

Add workflow for automatically update major tag on minor release

---

.eslintrc.json
__tests__/check.test.ts
__tests__/resources/repos.test.md
action.yml
jest.config.js
package-lock.json
package.json
src/check.ts
tsconfig.json

Inputs read by `core.getInput` are initialized as `''` if they aren't present. However we are handling them as `undefined`:
```ts
const file: string | undefined = core.getInput('repos-file')
```
First of all `action.yml` shouldn't contain any `default: ''` for non-required inputs, since that is already the initial value.
Second of all inputs should be read as `string` and checked using:
```ts
const file: string = core.getInput('repos-file')
if (!file) {
//Input is not provided
}
```
A whole suite of tests for the `check.repoFiles()` method has been included so we ensure this error won't happen again in the future.
This fixes #21

Fix bug in handling `repos-file` input

---

src/files.ts
src/main.ts

Some runners may not allow creating folders/files under `/opt`, therefore it is more accurate to create Scala Steward's workspace under the OS home directory.
This was discovered by @MVP in #41

Create Scala Steward workspace under home dir instead of `/opt`

---

action.yml
package.json
tsconfig.json

- Use `ES2019` for Typescript compilation.
- Remove `outDir` & `rootDir` from `tsconfig.json` and tell `ncc` which files to build ([it can be directly pointed to Typescript files](https://github.com/vercel/ncc#with-typescript)).
- Compile current `main.ts` into `dist/main.js` instead of `dist/index.js`.

Use `ES2019` for Typescript compilation & change name of compiled file

---

action.yml
package.json
src/coursier.ts
src/main.ts
src/post.ts
src/workspace.ts

Files created by this action are left behind once the action is over. This doesn't affect normal runs (those run in Github machinery) but [is a problem for those using a self-hosted runner](https://github.com/scala-steward-org/scala-steward-action/issues/52#issuecomment-638924197).
Using the [`post` step of a Github Action](https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post) we can run a cleanup of files created by the action. In particular, it will be deleted both the Scala Steward workspace and the Coursier binary.
This partially solves #52, caching of the workspace will be solved in a subsequent PR.

Add `post` step to cleanup files created by the action

---

package-lock.json
package.json
src/main.ts
src/workspace.ts

Add caching for the whole `workspace` folder where Scala Steward stores repositories and their metadata so subsequent builds are faster.
[Here](https://github.com/alejandrohdezma/test-scala-steward-action/runs/748984721?check_suite_focus=true) is an example run with this new feature.
This PR fixes #52

Save/restore Scala Steward workspace to/from cache

---

src/github.ts

fix this issue
https://github.com/scala-steward-org/scala-steward-action/issues/104
This crash is triggered by `core.debug (error)`.
in my case,  i used `{secrets.GITHUB_TOKEN}` in github actions job.
`{secrets.GITHUB_TOKEN}` was invalid for using scala-steward-action bacause  this is not have permission for access `/user`.
and octokit throw exception.
i think this fix is good for troubleshooting in setup steward-action.

fix Crashing when called getAuthUser was failed

---

README.md

I setup scala-steward-action for [multiple repositories](https://github.com/scala-steward-org/scala-steward-action#updating-multiple-repositories), but I didn't realize that need to [checkout](https://github.com/actions/checkout).
It's an elementary mistake, but I think it would be more user-friendly to add a checkout step to the example.

Fix multiple repositories example

---

README.md
action.yml
src/main.ts

i Implemented this! https://github.com/scala-steward-org/scala-steward-action/issues/62
but i am not confident in my english writing for documentation.

feature cache ttl option

---

README.md

This is relatively new: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch
I think that this is a more appealing approach since it provide a nice UI:

Suggest using workflow_dispatch as a manual trigger

---

src/coursier.ts
src/main.ts

- Rename `coursier#install` to `coursier#selfInstall`
- Add a new method to allow installing apps through coursier with [`cs install`](https://get-coursier.io/docs/cli-install)
- Install [Scalafmt](https://scalameta.org/scalafmt/) before running Scala Steward.
This PR fixes #187

Install `Scalafmt` before running Scala Steward

---

src/github.ts
src/main.ts

GitHub Actions provide `secrets.GITHUB_TOKEN` by default.
https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow
But `github.users.getAuthenticated()` throw Error if `token` is `secrets.GITHUB_TOKEN`, so I have set explicit github-actions bot login, email and name.
https://github.community/t/github-actions-bot-email-address/17204/6
Here is an example repo.(I have't set any tokens in this repo. I have use only default `GITHUB_TOKEN`)
- https://github.com/xuwei-k/scala-steward-test-1/commit/d871418d30c944d750cddc4ae894fc46090a0f64
- https://github.com/xuwei-k/scala-steward-test-1/runs/1265240619#step:5:35
- https://github.com/xuwei-k/scala-steward-test-1/pull/1

use github-actions[bot] account if token is "secrets.GITHUB_TOKEN"

---

src/coursier.ts

- Ensure installed coursier apps are installed in a directory that is already in the path (like the one courier gets installed to).
- Instead of showing a log group like `Installing my-app...` show the version of the installed app
Thanks to @hmemcpy for [discovering](https://twitter.com/hmemcpy/status/1329047672527986690) this error.

Fix a bug when installing Scalafmt that was preventing the action from working

---

README.md

This updates the links to the Scala Steward repo from `fthomas/scala-steward` to `scala-steward-org/scala-steward`. I also removed the Credit section since it only mentions me. Maybe linking to https://github.com/scala-steward-org/scala-steward#contributors and mentioning the folks that contributed to the GH Action would be nicer.

Update links to Scala Steward repo

---

README.md
src/coursier.ts

This PR enables starting Scala Steward with the `LOG_LEVEL=TRACE` java option if ["step debug logging"](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging) is activated. 
For this you must set the following secret in the repository that contains the workflow: `ACTIONS_STEP_DEBUG` to `true` (as stated in GitHub's documentation).

Auto enable `LOG_LEVEL=TRACE` in Scala Steward if using "step debug logging"

---

README.md
action.yml

It was released yesterday: [Scala Steward 0.13.0](https://github.com/scala-steward-org/scala-steward/releases/tag/v0.13.0).

Update to Scala Steward 0.13 as default version

---

README.md
action.yml
src/main.ts

Currently there is no way to set Scala Steward's `--git-author-signing-key` option. This adds an optional `signing-key` configuration parameter.

Add signing-key input option

---

src/main.ts

Scala Steward workspace should always be restored (even if `cache-ttl` is set to `0`). If not, old PRs won't be closed.
Thanks to @milanvdm for helping out finding this :)

Workspace should always be restored

---

src/main.ts

This change makes sure the workspace is saved, regarding the outcome of launching Scala Steward, as suggested by @fthomas [here](https://github.com/scala-steward-org/scala-steward-action/issues/367#issuecomment-1146740861).

Save workspace always

---

README.md
src/coursier.ts
src/main.ts

The environment variables for starting Scala Steward on debug mode must be present on the environment (instead of passing them to coursier). Also, the environment variable to check if debug mode is enabled has changed: it is now always `RUNNER_DEBUG=1` (even when you set the `ACTIONS_STEP_DEBUG` variable GitHub will replace it with `RUNNER_DEBUG`).
Fixes #388.

Fix debug mode

---

src/main.ts
src/mill.ts

**The problem**
So when using this action I was a little thrown off that it was failing with:
```
java.io.IOException: Cannot run program "mill" (in directory "/home/runner/scala-steward/workspace/repos/scalacenter/bloop-config"): error=2, No such file or directory
```
I would expect the action to ensure what's needed is installed. I'm assuming no one hits on this for sbt due to it always being there in the ubuntu image.
**The fix**
This change ensures that `mill` is always there and installed.
**NOTE**
Sort of opening this up just to discuss since it came up in https://github.com/scala-steward-org/scala-steward/issues/2803. If this is an ok approach I'll add some docs. Also, I have no idea how to test this using the tool-cache. Any ideas how to test this? I see the other installations …

feat: ensure Mill is installed

---

src/mill.ts

It looks like there are situations when dealing with mounted drives
you get the following error:
```
Error: EXDEV: cross-device link not permitted, rename '/runner/_work/_temp/9b722d14-6935-45f9-ab1a-526911088cbe' -> '/home/runner/bin/mill'
```
From googling around it looks like we can avoid this by instead
moving the file first and then removing it.
For reference
- https://stackoverflow.com/questions/44146393/error-exdev-cross-device-link-not-permitted-rename-nodejs
- https://github.com/shelljs/shelljs/issues/191
Fixes: #421

fix: instead of moving mill cp and then remove

---

.all-contributorsrc
action.yaml
src/action/pre.ts
src/modules/coursier.ts

We were using an outdated link for downloading Coursier.
With the new version we can also benefit from `cs uninstall` to remove the data installed by Coursier.

Update Coursier installation process

---

src/modules/coursier.ts

These are already removed by `cs uninstall`. They are causing a `Nothing to remove` error to appear on Action pages.

Remove unneeded code

---

action.yaml
src/action/pre.ts
src/modules/coursier.ts
src/modules/mill.ts

It seems installing JVM causes many problems on self-hosted runners. So instead of ensuring a JVM is installed, we leave that responsibility to the user.

Stop installing JVM

---

src/action/main.ts
src/modules/workspace.ts

This is the complementary PR for https://github.com/scala-steward-org/scala-steward/pull/3071.
While that PR _creates_ the summary report, this is the PR that links up to GitHub's [`core.summary`](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#:~:text=core.summary ) workflow command (as suggested by @alejandrohdezma in https://github.com/scala-steward-org/scala-steward/pull/3071#pullrequestreview-1466649042), to _display_ the report in [GitHub's Job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/#:~:text=core.summary).
In this change, if the `run-summary.md` file generated by the Scala Steward JVM process is found, it's written to the GitHub  summary - if it's not found, that's not regarded as an error, …

Display GitHub Action Job Summary

---

src/modules/workspace.test.ts
src/modules/workspace.ts

This was something we missed from https://github.com/scala-steward-org/scala-steward-action/pull/502 - because the `run-summary.md` file (introduced by https://github.com/scala-steward-org/scala-steward/pull/3071) is saved to the Scala Steward workspace, and almost the entire workspace is persisted to cache by Scala Steward's GitHub Action, the report would be persisted until the _next_ run of the GitHub Action.
Conceivably, if the next run went wrong somehow and didn't overwrite the old file, the _old_ summary could get reported against the subsequent run, which would be bad.
The fix here is to delete the summary at the `saveWorkspaceCache()` step, which occurs after the summary has been transferred to the `GITHUB_STEP_SUMMARY` file by calling `core.summary()`.

Don't persist the `run-summary.md` file beyond its own run

---

README.md

When debugging the behaviour of Scala Steward in production, it can be helpful to run Scala Steward locally, while **mimicking the settings used by the Scala Steward GitHub Action**, so that a debugger can be attached - here's a link to some docs we wrote at the Guardian on this, which may be helpful to others:
https://github.com/guardian/scala-steward-public-repos/blob/main/running-locally.md

Add link to docs on how to run locally to attach a JVM debugger

---

action.yml
package-lock.json
package.json
src/action/main.ts
src/modules/input.ts

* use the given URL to get tokens
* use the variable `github.api_url` as default value (https://docs.github.com/en/actions/learn-github-actions/contexts)
Fixes the secretOrPrivateKey must be an asymmetric key error
using the workaround from https://github.com/octokit/auth-app.js/issues/465#issuecomment-1549150080
fixes: #517
closes: #521

use github API URL

---

README.md
action.yml
src/action/main.ts
src/modules/input.test.ts
src/modules/input.ts

I would like to add the scala-steward's flag `max-buffer-size`.
But I have no idea how to test this.

Add flag max-buffer-size

---

action.yml
src/action/main.ts
src/modules/coursier.ts
src/modules/input.test.ts
src/modules/input.ts

copy of #467 
tested with released version from my fork, successfully integrated with google cloud artifact registry with:
```
- name: Fetch gar-coursier
id: fetch_gar_coursier
run: |
export GAR_COURSIER_CLASSPATH=$(cs fetch --classpath "dev.rolang:gar-coursier_2.13:0.1.3");
echo "GAR_COURSIER_CLASSPATH=$GAR_COURSIER_CLASSPATH" >> $GITHUB_ENV;
- name: Launch Scala Steward
uses: lgmyrek/scala-steward-action@v2
with:
...
extra-jars: ${{ env.GAR_COURSIER_CLASSPATH }}
cache-ttl: 0minute
```

Add support for setting Coursier's --extra-jars option when launching Scala Steward

---

README.md

Resolves: https://github.com/scala-steward-org/scala-steward-action/issues/591
Can confirm it works with https://github.com/apache/pekko/actions/runs/8579986686

Document JAVA_OPTS

---

src/action/main.ts

Fixes #632
Cache from previously failed attempts is restored
And then it's also saved if current attempt fails

Save workspace cache when run failed

---

src/action/main.ts
src/modules/workspace.test.ts
src/modules/workspace.ts

Fixed https://github.com/scala-steward-org/scala-steward-action/issues/625
`--git-ask-pass` file is now updated every 50 minutes, as the default token expiration is 1 hour
And workflow can now run longer than one hour with no issues

Refresh token every 50 minutes

---

src/action/main.ts
src/modules/workspace.ts

Fixes https://github.com/scala-steward-org/scala-steward-action/issues/634

Cancel GitHub token refresh at the end

---

README.md

`ubuntu-latest` or `ubuntu-22.04` runner tags are used on README.md. I think it is better that only `ubuntu-latest` is documented. But `sbt` was removed from the `ubuntu-latest` (equals `ubuntu-24.04`) runner image.  https://github.com/actions/runner-images/issues/10636
This PR makes a README.md fix to run on `ubuntu-latest` and install `sbt`. Thanks!

Fix README.md to run on ubuntu-latest and install sbt

---

src/action/main.ts
src/modules/workspace.test.ts
src/modules/workspace.ts

Scala Steward's GitHub Action Job Summary, which reports success or failure of individual repos in the Scala Steward run, was added with https://github.com/scala-steward-org/scala-steward/pull/3071 in June 2023, followed up by https://github.com/scala-steward-org/scala-steward/pull/3088, which ensured that old `run-summary.md` files couldn't persist in the workspace cache (where they might become misleading), by purging them before the cache was saved.
Unfortunately https://github.com/scala-steward-org/scala-steward-action/pull/631 (released with [v2.67.0](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.67.0) in September 2024) unintentionally broke the outputting of the Job Summary, because it [moved](https://github.com/scala-steward-org/scala-steward-action/pull …

Fix loss of `run-summary.md` in GHA Job Summary

---

README.md
src/modules/coursier.ts

Ensure SBT is installed using Coursier

---

README.md
action.yml

This updates Mill to the latest version. This version is now a script that is able to run different Mill versions depending on the version set in project-specific `.mill-version` files.

Update Mill to 0.12.5

---

src/action/main.ts

Scala Steward's GitHub Action Job Summary, which reports success or failure of individual repos in the Scala Steward run, was added with https://github.com/scala-steward-org/scala-steward/pull/3071 in June 2023, but unfortunately, the Summary is currently _not_ output if Scala Steward exits with a failure code - which is the time when it would be most useful to see a summary of which repos succeeded or failed!
This was due to the summary-outputting code being placed _inside_ the `try` block, immediately after the call to `coursier.launch()` that runs Scala Steward - and `coursier.launch()` throws an error if the exit-code is non-zero (by default, Scala Steward exits with a non-zero exit code if _any_ repo fails, even when all other repos are successfully processed): …

Output Run Summary even if Scala Steward exits with failure code
